# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: install dependencies
        run: npm install
      - name: generate build
        run: npm run build --prefix client
        env:
          CI: false
      - name: look around
        run: ls
      - name: copy files
        run: |
          for f in server.js routes database; do cp -r $f ~/cs340-project; done;
          cp -r ./client/build ~/cs340-project/client
          cd ~/cs340-project
          forever stopall
          forever start server.js
          

